### ISSUE TITLE
Bug in stock reduction

### ISSUE THREAD

**Issue by mitzeitundohne** [alexmigf/stock-locations-for-woocommerce#43] opened 2020-11-12 15:20 UTC
Hi

Great plugin! Thanks.

One bug: if no location is selected during check out in cart (frontend), then u add the location in backend in admin order list in corresponding order, then the Stock will be reduced twice with the same amount. 
Thia make sense because woocomerce will reduce Stock by Handover of order already. If afterwards i select an location, the Stock is again reduced.

Can u fix this?

Rgds

**Comment by WarenGonzaga** [comment] 2020-11-12 20:19
@mitzeitundohne this is duplicate of #35

**Comment by mitzeitundohne** [comment] 2020-11-12 20:30
i dont think so. the error is different. you talk about the cancel and that amount is not written back to WC stock.
my problem is during order and creation of the order. the result is different too: the stock will be reduced by double of the value. 
but of course its very related. both issues are connected to WC stock management that is not covered.

**Comment by alexmigf** [comment] 2020-11-12 20:43
I will try to add this to the next release, just need some time.

**Comment by mitzeitundohne** [comment] 2020-11-12 21:09
This means days. Weeks months? 🙈

**Comment by alexmigf** [comment] 2020-11-12 21:24
I hope next week :)

**Comment by alexmigf** [comment] 2020-11-12 22:09
@mitzeitundohne  what are the settings for those 2 locations (a & b)? And also your plugin settings?

**Comment by mitzeitundohne** [comment] 2020-11-12 22:34
All is set to no.

Tried "yes" too with different combinations. No success. Prio Was 0. 

As mentioned above: in any case of changes of stock to wc does his job regarding stock, but u miss to sync. 
In my Case u finally reduce stock a 2nd time if i adapt the location amount from 0 to 1 inside the order in backend. First reduction happen during press of "order now" by customer in frontend and initial creation of order in backend. 

Similar is the case #35  mentioned above. Here the Update in your section on product page runs, but stock in ATUM view is not changed. It stays like no return happened. Then of course u throw  an error of missmatch

**Comment by alexmigf** [comment] 2020-11-12 22:45
@mitzeitundohne thanks, I will look into that.

**Comment by mitzeitundohne** [comment] 2020-11-12 23:02
Maybe one last hint: in customer on frontend do not define a location on card then no location is handed over to order. In this case this happens. 
Of course in u configure on backend to not show location info on frontend, then no location is handed over too. Same result. 
Just if i turn on Display of location info on prduct page on frontend then location info is handed over to order. 

But location info in my case confuse my customers. For them it doesnt matter because goods are shipped in any case. But for me in backend location info is nice especially if i can adapt it.

I think the missing location assignement during Initial creation of order (frontend &backend) lead u trigger the change of All amounts again if location is Finally added in backend with saving button (admin order detail view)

**Comment by mitzeitundohne** [comment] 2020-11-12 23:04
Sorry for typos...in should be if in some cases. 

 ..writing frontend mobil with german correction;)

**Comment by alexmigf** [comment] 2020-11-17 22:08
@mitzeitundohne 

Can you please replace your current version with the master branch and see if it fixes the issue? Download here https://github.com/alexmigf/stock-locations-for-woocommerce

**Comment by WarenGonzaga** [comment] 2020-11-18 04:30
@alexmigf I probably give it a shot... let you know

**Comment by mitzeitundohne** [comment] 2020-11-18 14:44
hi alex...i am not that familar with structure of files: ftp looks different then folder structure in git. 
this is to time consuming for me to check. just make the rollout of zip file and i check it with that. 
important is that you fix the issue from 35 too because this is somehow similar.

**Comment by alexmigf** [comment] 2020-11-18 20:56
Hi @mitzeitundohne the #35 is different, not the same thing or related.

Can you please send me an [email](mailto:alexmigf@gmail.com)? I will send you a copy to test.

**Comment by mitzeitundohne** [comment] 2020-11-20 12:53
this is solved with latest update.

**Closed** 2020-11-20 18:01 UTC
